### ISSUE TITLE
mgmt.go::searchOidHandler assumes Cassandra

### ISSUE THREAD

**Issue by johnseekins** [cloudmazing/lfs-server-go#14]
func (a *App) searchOidHandler(w http.ResponseWriter, r *http.Request) {
        searchedOid := r.URL.Query().Get("oid")
        if len(searchedOid) < 1 {
            writeStatus(w, r, 404)
        }
        sess := NewCassandraSession()

That's not great if someone is using a different meta store. Unless this functionality is somehow only exposed when using Cassandra.

**Comment by memikequinn** [comment]
@johnseekins Good point.  Was an oversight on my part and should be put in an abstraction layer for searches that maps to [findAllOids](https://github.com/cloudmazing/lfs-server-go/blob/master/cassandra_meta_store.go#L107) and [Objects](https://github.com/cloudmazing/lfs-server-go/blob/master/meta_store.go#L261).

**Comment by johnseekins** [comment]
I *think* this fixes the problem:

```
    if Config.CassandraConfig.Enabled == 'true' {
	   sess := NewCassandraSession()
	   defer sess.Client.Close()
	   cs, err := NewCassandraMetaStore(sess)        
    } else {
        cs, err := NewMetaStore(Config.MetaDB)
    }
```
