### ISSUE TITLE
Using this for GitLab? PostgreSQL support

### ISSUE THREAD

**Issue by dosire** [cloudmazing/lfs-server-go#5]
How would you feel about GitLab using this as well?

Would you be open to us adding PostgreSQL support for the metadata store?

**Comment by dosire** [comment]
Mmm, is there a BoltDB per repo or for the whole server? If it is per repo we can just use that.

**Comment by memikequinn** [comment]
@dosire I think it would be great if gitlab uses this, as well as adding in PostgreSQL support.  
There is not a BoltDB per repo (not a bad idea though) but you would lose the ability to share objects across projects.  Do you see sharing objects across repos (ex. forking a repo) as a future or current need?

**Comment by dosire** [comment]
I'm not sure if sharing objects across repo's is a need. But glad to hear you're open to using PostgreSQL.

**Comment by dosire** [comment]
@memikequinn Thanks for the close, we ended up writing our own.
